Animations gestures
olaokoroafor/FoodFriends pull request #77
Opened 2022-07-25 19:24 UTC by olaokoroafor

Description:
 - added like and togo animation
 - double tap to like feature

2022-07-26 15:36 UTC, nammyfb requested changes

2022-07-26 15:36 UTC, nammyfb commented on FoodFriends/app/src/main/java/com/example/foodfriends/activities/SignUpActivity.java
> +        String[] state_list = new String[]{"Select State", "AK", "AL", "AR", "AZ", "CA", "CO", "CT", "DC", "DE", "FL", "GA",
you could have this as a static array. 

Also camelCase :)

2022-07-26 15:36 UTC, nammyfb commented on FoodFriends/app/src/main/java/com/example/foodfriends/activities/SignUpActivity.java
> +            root = new JsonParser().parse(new FileReader("../misc/CitiesByState.json"));
the json file could be a static

2022-07-26 18:27 UTC, nammyfb commented on FoodFriends/app/src/main/java/com/example/foodfriends/misc/CitiesByState.json
> +{
This should be in /res

2022-07-26 19:54 UTC, olaokoroafor commented on FoodFriends/app/src/main/java/com/example/foodfriends/activities/SplashActivity.java
>                          Intent i = new Intent(SplashActivity.this, LogInActivity.class);
Where would you suggest I put this private class member?/ I'm not sure how it would be done. Should I make a new class?

2022-07-27 17:08 UTC, nammyfb commented on FoodFriends/app/src/main/java/com/example/foodfriends/activities/SplashActivity.java
>                          Intent i = new Intent(SplashActivity.this, LogInActivity.class);
Like a new value in the same class :) 

ex: 

`public AnimationListener animationListener = new Animation.AnimationListener() {
....
....
}
`

then you could just inject that during the onCreate. Makes for less busy method.

2022-07-27 17:53 UTC, olaokoroafor commented on FoodFriends/app/src/main/java/com/example/foodfriends/activities/SplashActivity.java
>                          Intent i = new Intent(SplashActivity.this, LogInActivity.class);
thanks!! just did this!

2022-07-27 21:20 UTC, nammyfb commented on FoodFriends/app/src/main/java/com/example/foodfriends/activities/SignUpActivity.java
> +    private final static String[] stateList = new String[]{"Select State", "Alaska", "Alabama", "Arkansas", "Arizona", "California", "Colorado", "Connecticut", "District of Columbia", "Delaware", "Fl
you could just use the Map.keys list instead :)

2022-07-27 21:33 UTC, merged

2022-07-27 21:33 UTC, nammyfb approved these changes